#!/usr/bin/env python3
"""Refresh index.html's CSP hashes after a reviewed JavaScript change.

No network or third-party dependencies. --check is the CI verification mode.
Only fixed, source-controlled inline handlers are permitted; generated handlers
with interpolated values must use addEventListener instead.
"""
import argparse
import base64
import hashlib
import html
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
START = '<!-- INDEX_CSP_START: generated by scripts/update-index-csp.py -->'
END = '<!-- INDEX_CSP_END -->'
SCRIPT = re.compile(r'<script\b([^>]*)>([\s\S]*?)</script>', re.I)
HANDLER = re.compile(r'\son[a-z]+\s*=\s*(?:"([^"]*)"|\'([^\']*)\')', re.I)


def digest(source):
    return "'sha256-" + base64.b64encode(hashlib.sha256(source.encode()).digest()).decode() + "'"


def render(source):
    scripts = sorted({digest(match[2]) for match in SCRIPT.finditer(source)
                      if match[2].strip() and not re.search(r'\bsrc\s*=', match[1], re.I)})
    handlers = set()
    for match in HANDLER.finditer(source):
        code = html.unescape(match[1] if match[1] is not None else match[2])
        if '${' in code:
            raise ValueError('Move dynamic inline event code to addEventListener: ' + code)
        handlers.add(digest(code))
    directives = [
        "default-src 'self'",
        "base-uri 'none'",
        "object-src 'none'",
        "script-src 'self' https://www.gstatic.com/firebasejs/ https://www.gstatic.com/recaptcha/ "
        "https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://apis.google.com/ "
        "https://cdn.jsdelivr.net/npm/chart.js@4.5.1/dist/chart.umd.min.js "
        "https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@2.0.1/dist/chartjs-plugin-annotation.min.js "
        "https://cdn.jsdelivr.net/npm/@zxing/browser@0.1.5/umd/zxing-browser.min.js " + ' '.join(scripts),
        # Legacy fixed handlers are individually approved by hash. This does not
        # permit arbitrary inline JavaScript or interpolated database values.
        "script-src-attr 'unsafe-hashes'\n        " + '\n        '.join(sorted(handlers)),
        "style-src 'self' 'unsafe-inline'",
        "img-src 'self' data: blob: https://raw.githubusercontent.com https://www.gstatic.com https://www.google.com",
        "connect-src 'self' https://*.googleapis.com https://*.cloudfunctions.net "
        "https://*.firebaseio.com wss://*.firebaseio.com https://alcoholaway.firebaseapp.com "
        "https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://www.gstatic.com https://api.open-meteo.com",
        "frame-src https://alcoholaway.firebaseapp.com https://www.google.com/recaptcha/ "
        "https://recaptcha.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/",
        "worker-src 'self' blob:",
        "font-src 'self' data:",
        "media-src 'self' blob:",
        "manifest-src 'self'",
        "form-action 'self'",
        'upgrade-insecure-requests',
    ]
    policy = ';\n        '.join(directives)
    block = f'{START}\n    <meta http-equiv="Content-Security-Policy" content="{policy}">\n    {END}'
    if START in source:
        return re.sub(re.escape(START) + r'[\s\S]*?' + re.escape(END), lambda _: block, source, count=1)
    marker = '<meta charset="UTF-8">'
    assert source.count(marker) == 1
    return source.replace(marker, marker + '\n    ' + block, 1)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'index.html'
    original = path.read_text(encoding='utf-8')
    updated = render(original)
    if args.check:
        if original != updated:
            raise SystemExit('CSP hashes are stale. Run: python3 scripts/update-index-csp.py')
        print('index.html CSP hashes are current.')
    else:
        path.write_text(updated, encoding='utf-8')
        print('Updated index.html CSP hashes.')
